# Site settings
title: Chinsyo | 晨晓
header-img: img/home-bg.jpg
email: chinsyo@qq.com
description: "Noob & Geek | 我心匪石"
keyword: "王晨晓, Blog, 博客, 苹果, iOS, macOS, Python, 编程, 开发"
url: "https://chinsyo.com"              # your host, for absolute URL
dir: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username: chinsyo
github_username: chinsyo
mailme_username: lPf8-frn7fvU5eW69-v5


# Repositories
repository: chinsyo/chinsyo.github.io



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty 
paginate: 10
exclude: 
  - ".gitignore"
anchorjs: true
defaults:
  -
    scope: 
      path: ""
      type: posts
    values:
      layout: post
      author: Chinsyo
  -
    scope:
      path: ""
      type: projects
    values:
      layout: subject
      author: Chinsyo

# if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: 
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-github-metadata



# Collections
collections:
  projects:
    output: true
    permalink: /project/:path



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: chinsyo



# Google Analytics
ga_track_id: "UA-131370814-1"            # Format: UA-xxxxxx-xx
# adsense_id: "ca-pub-3082878493327361"


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Noob & Geek<br>我心匪石"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: 
  - 
    title: "OneV's Den"
    subtitle: "嗨，我是王巍 (@onevcat)，一名 iOS 开发者。"
    href: "https://onevcat.com/"
  -
    title: "Garan no dou"
    subtitle: "一只魔法师的工坊"
    href: "https://blog.ibireme.com/"
  -
    title: "火辣辣"
    subtitle: "前端博客"
    href: "http://huolalaweb.com/"
  -
    title: "极客兔兔"
    subtitle: "致力于分享有趣的技术实践"
    href: "https://geektutu.com/"
  -
    title: "fengxianqi"
    subtitle: "静心沉淀，思考进阶。"
    href: "https://www.fengxianqi.com/"
  -
    title: "rffan 实验室"
    subtitle: "一个高端大气上档次的网站"
    href: "https://rffanlab.com/"
  -
    title: "挨踢极客"
    subtitle: "人生苦短，我想编程"
    href: "https://blog.itjk.me/"
  -
    title: "邱青岑的个人博客"
    subtitle: "有幸与你见证技术的变迁"
    href: "https://www.imwhite.com.cn/"
  -
    title: "麦田博客"
    subtitle: "记录技术与生活。"
    href: "https://www.myting.net/"
  -
    title: "阿里小太阳"
    subtitle: "小太阳昌仔 永远照耀你"
    href: "http://haoufo.com"
  -
    title: "码农的自留地"
    subtitle: "码农的自留地"
    href: "https://quxiaolei.github.io"
  -
    title: "曲奇泡芙"
    subtitle: "stay interesting.."
    href: "http://weng.ai"
