# Site settings
title: 晨晓 | Chinsyo
seo-title: 王晨晓的博客 | Chinsyo Blog
header-img: img/home-bg.jpg
email: chinsyo@qq.com
description: "王晨晓的博客 | 开发工程师,关注数据、设计、效率"
keyword: "王晨晓, Blog, 博客, 苹果, iOS, macOS, Python, 编程, 开发"
url: "https://chinsyo.com"              # your host, for absolute URL
dir: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username: chinsyo
github_username: chinsyo
mailme_username: lPf8-frn7fvU5eW69-v5



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty 
paginate: 10
exclude: 
  - ".gitignore"
  - "README.md"
anchorjs: true
defaults:
  -
    scope: 
      path: ""
      type: posts
    values:
      layout: post
      author: Chinsyo

# if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: chinsyo



# Google Analytics
ga_track_id: "UA-131370814-1"            # Format: UA-xxxxxx-xx



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: |+
  Noob & Geek
  我心匪石
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: 
  -
    title: "芯盾技术团队"
    subtitle: "日月既往 不可复追"
    href: "https://coreshield.github.io/"
  -
    title: "月半兄的小站"
    subtitle: "Working on Android & Network Security"
    href: "https://yueban.github.io/"
  -
    title: "珞泽珈群"
    subtitle: "头顶的星空以及心中的道德定律"
    href: "https://www.jianshu.com/u/679d8deee5ae"
  -
    title: "曲奇泡芙"
    subtitle: "stay interesting.."
    href: "http://weng.ai"
  -
    title: "rffan 实验室"
    subtitle: "一个高端大气上档次的网站"
    href: "https://rffanlab.com/"
  -
    title: "极客兔兔"
    subtitle: "致力于分享有趣的技术实践"
    href: "https://geektutu.com/"
  -
    title: "fengxianqi"
    subtitle: "静心沉淀，思考进阶。"
    href: "https://www.fengxianqi.com/"
  -
    title: "挨踢极客"
    subtitle: "人生苦短，我想编程"
    href: "https://blog.itjk.me/"
  -
    title: "邱青岑的个人博客"
    subtitle: "有幸与你见证技术的变迁"
    href: "https://www.imwhite.com.cn/"
  -
    title: "麦田博客"
    subtitle: "记录技术与生活。"
    href: "https://www.myting.net/"
  -
    title: "码农的自留地"
    subtitle: "码农的自留地"
    href: "https://quxiaolei.github.io"

